Feature/fe launch checklist
wagtail/guide pull request #163
Opened 2022-10-20 12:22 UTC by nicklee

- Adds title and meta descriptions
- Add social media share info and image

2022-10-20 20:49 UTC, lb- commented on apps/core/templates/base.html
> +         <meta name="og:image" content="{{ current_site.root_url }}{% static 'images/social-image.png' %}">
```suggestion
        <meta name="og:image" content="{{ current_site.root_url }}{% static 'images/social-image.png' %}">
```

Just an extra space here I think

2022-10-21 21:52 UTC, thibaudcolas requested changes
I think there’s a bit more to do here, as we don’t have some of those fields. Also the favicon setup seems partial?

2022-10-21 21:52 UTC, thibaudcolas commented on apps/core/templates/base.html
> +        <meta name="twitter:description" content="{% if page.search_description %}{{ page.search_description }}{% else %}{{ page.listing_summary }}{% endif %}">
Same as above, we don’t have a `listing_summary` on this build.

2022-10-21 21:52 UTC, thibaudcolas commented on apps/core/templates/base.html
> +        <meta property="fb:app_id" content="{{ settings.utils.SocialMediaSettings.facebook_app_id }}" />
We don’t have this set up on this site, and likely never will.

```suggestion
```

2022-10-25 09:06 UTC, thibaudcolas approved these changes

2022-10-25 09:06 UTC, thibaudcolas commented on apps/core/templates/base.html
> +        <meta name="twitter:image" content="{{ current_site.root_url }}{% static 'images/social-image.png' %}">
I doubt this would work as our Webpack tooling doesn’t have support for images. I’ll move the file to the `public` folder later.

2022-10-25 09:06 UTC, merged

2022-10-25 09:17 UTC, thibaudcolas commented on apps/core/templates/base.html
> +        <meta name="twitter:image" content="{{ current_site.root_url }}{% static 'images/social-image.png' %}">
My bad, this works, just needs to use `manifest` for correctness. It wasn’t working in Gitpod for other reasons (site record)