Added ContentPage along with its template
wagtail/guide pull request #5
Opened 2022-06-12 08:41 UTC by Hitansh-Shah

I added a new app `content` and defined a new page `ContentPage` along with its template inside it. I added some restrictions like `max_count` and `subpage_types` to both `ContentPage` and `HomePage`. @allcaps

2022-06-13 05:59 UTC, allcaps requested changes
- The `*.pyc` files should not be in version control. Add them to the .gitignore
- Files that we don't use should be removed. We don't use views.py and test.py
- We've got two migration files. The rename is unnecessary and can be in the initial migration. Please recreate the migrations (drop your db and the migration files and run makemigrations)

2022-06-13 08:33 UTC, Hitansh-Shah commented
I have done the changes you requested. Please take a look @allcaps

2022-06-28 14:57 UTC, allcaps requested changes

2022-07-01 10:54 UTC, allcaps approved these changes

2022-07-01 10:55 UTC, merged